== Robots

=== Control

. Robots must be controlled autonomously. Using a remote control, manual control, or passing information (by external sensors, cables, wirelessly, etc.) to the robot is not allowed.

. Robots must be started manually by the team captain.

. Any pre-mapped type of dead reckoning (movements preprogrammed based on known locations or placement of features in the field) is prohibited.

. Robots must not damage any part of the field in any way.

[[construction]]
=== Construction

. The height of a robot must not exceed 25 cm.

. Robots may not have sensors or devices that enable them to 'see' over the walls.

. Any robot kit or building blocks, either available on the market or built from raw hardware, may be used as long as the design and construction of the robot are primarily and substantially the students' original work.

. Robots like drones or hovercrafts are prohibited in the challenge due to safety reasons.

. Teams are not permitted to use commercially produced robot kits or sensor components specifically designed or marketed to complete any single primary task of RoboCupJunior Rescue. Robots that do not comply will face immediate disqualification from the tournament. If there is any doubt, teams should consult the tournament organizer before the competition.

. Any lasers must not be used.

. Robots may incur damage by falling off the field, making contact with another robot, or contacting field elements. The tournament organizers, referee, volunteers cannot anticipate all potential situations where damage to the robot may occur. Teams should ensure that all active elements on a robot are adequately protected with resistant materials. For example, teams must protect electrical circuits from all human contact and direct contact with other robots and field elements.

. When batteries are transported, moved, or charged, it is strongly recommended that safety bags be used. Reasonable efforts should be made to ensure that robots avoid short circuits and chemical or air leaks.

. Robots must be equipped with a handle that is to be used to pick them up during the scoring run.

. Robots must be equipped with a single physical binary switch/button (with exception of buttons that are a part of commercial controllers), clearly visible to the referee, for starting the robot at the beginning of the run and when a lack of progress (LoP, see 5.5) occurs. The procedure performed after a LoP occurs can only include this button and at most one more switch for cutting the power. Teams have to notify the referee about their LoP procedure before each scoring run, and only this procedure is allowed to be performed after a LoP.

. The robot must be equipped with two specific LEDs that are dedicated only for identifying victims. These LEDs must be red and green. The LED must be clearly visible to the referee.


=== Team

. Each team must have only one robot on the field.

. Each team must comply with the regulations set by the regional organizers regarding the number of team members and the age of each member.

. Each team member must explain their work and have a specific technical role.

. A student can be registered on only one team across all RoboCupJunior leagues/sub-leagues.

. A team can only participate in one league/sub-league across all RoboCupJunior leagues/sub-leagues.

. Mentors/parents are not allowed to be with the students during the competition. The students will have to govern themselves (without a mentor’s supervision or assistance) during the long stretch of hours at the competition.

=== Inspection

. A panel of referees will scrutinize the robots before the start of the tournament and at other times during the competition to ensure that they meet the constraints described in these rules.

. Using a robot similar to another team’s robot from a previous year or the current year is illegal.

. The team’s responsibility is to have their robot re-inspected if modified at any time during the tournament. 

. Students will be asked to explain their robot’s operation to verify that its construction and programming are their own work.

. Students will be asked about their preparation efforts. The RoboCupJunior Rescue Committee may request them to answer surveys and participate in videotaped interviews for research purposes.

. All teams must complete a web form before the competition if requested by the organizers. This is to help the judges prepare better for the interview. The organizers will instruct teams in advance on how to submit the form.

. All teams must submit their source code, if requested. 
However, the organizers will not share it with other teams without the team’s permission.

=== Violations

. Any violations of the inspection rules will prevent the offending robot from competing until modifications are made, and the robot passes inspection.

. Teams must make modifications within the schedule of the tournament, and teams cannot delay tournament play while making modifications.

. Suppose a robot fails to meet all specifications (even with modifications). In that case, it will be disqualified from that game (but not from the tournament).

. No mentor assistance is allowed during the competition. (See <<code-of-conduct>>)

. Any rule violations may be penalized by disqualification from the tournament or the game or result in a loss of points at the discretion of the referees, officials, or RoboCupJunior Rescue Committee.
