== Play

=== Pre-game Practice

. When possible, teams will have access to practice fields for calibration and testing throughout the competition.

. Whenever there are dedicated independent fields for competition and practice, it is at the organizers' discretion if testing is allowed on the competition fields.

=== Humans

. Teams should designate one of their members as 'captain' and another as 'co-captain'. Only these two team members will be allowed access to the competition fields unless directed by a referee. Only the captain can interact with the robot during a scoring run.

. The captain can move the robot only when they are told to do so by a referee.

. Other team members (and any spectators) within the vicinity of the competition field must stand at least 150 cm away from the field unless directed by a referee.

. No one is allowed to touch the fields intentionally during a scoring run.

. All pre-mapping activities will immediately disqualify the robot for the round. Pre-mapping is the act of humans providing the robot with information about the field (e.g., location of walls, location of black/silver tiles, location type of victims, etc.) before the game.

[[start-of-game]]
=== Start of Game

. Each team has a maximum of 6 minutes for a game. The game includes the time for calibration and the scoring run.

. Calibration is defined as taking sensor readings and modifying a robot’s program to accommodate such sensor readings. Calibration does not count as pre-mapping.

. The scoring run is defined as the time when the robot is moving autonomously to navigate the field, and the referee will record the scores.

. A game begins at the scheduled starting time, whether or not the team is present or ready. Start times will be posted around the venue.

. Once the game has begun, the robot is not permitted to leave the competition area.

. Teams may calibrate their robot in as many locations as desired on the field, but the clock will continue to run. Robots are not permitted to move on their own while calibrating.

. Before a scoring run begins, the referee will roll a standard 6-sided dice or another method of randomization set by the organizers to determine the location of the black and silver tiles. Organizers will not reveal the position of the black and silver tiles to the team until they are ready to start a scoring run. Referees will ensure the combination of black tile placements in a field layout is 'solvable' before a robot begins a scoring run.

. Before a scoring run begins, the referee can change any walls of the field (see <<path>>).

. Once a team is ready to start a scoring run, the team must notify the referee. To start a scoring run, the robot is placed on the start tile of the course, as indicated by the referee. Once a scoring run has begun, no more calibration is permitted, including changing code/code selection.

. Teams may choose not to calibrate the robot and immediately start the scoring run instead.

. Once the robot starts moving as the scoring run begins, a referee will place the black  and silver tiles, except the starting tile.


[[run]]
=== Scoring Run

. Modifying the robot during a scoring run is prohibited, which includes remounting parts that have fallen off.

. Any parts the robot loses intentionally or unintentionally will be left on the field until the game ends. Team members and referees cannot move or remove elements from the field during a scoring run.

. Teams cannot give their robot any information about the field. A robot is supposed to recognize the field elements by itself.

. A 'visited tile' means that more than half of the robot is inside the tile when looking from above.

=== Lack of Progress

. A lack of progress occurs when:
.. the team captain declares a lack of progress.
.. a robot visited the black tile. See the definition of visited tile on <<run>>.
.. a robot damages the field.
.. a team member touches the field or their robot without permission from a referee.

. In the event of a lack of progress, the robot must return to the last visited checkpoint (or the start tile if it never reached a checkpoint). The robot can be installed in any direction. For the definition of the visited tile (see <<run>>).

. After a lack of progress, only the LoP procedure explained to the referee before the run start is allowed to be performed (see <<construction>>).

[[scoring]]
=== Scoring

. To successfully detect a victim, the robot must visit from other tile and stop on the victim and blink with the specific LED (see Section 4.3, “Construction”) that is clearly visible to the referee for the full 5 seconds while stationary. The blink interval (ON: 500ms, OFF: 500ms) must be followed to successfully detect a victim.

. Points are rewarded for each Successful Victim detection in the field. 

.. For victims located on a linear tile. :  10 points 
.. For victims located on a floating tiles :  30 points

+
Some tiles change between floating or linear depending on the adjacent black and silver tiles. The field designer must remember this rule when deciding on the location of the black and silver tiles. They can be changed during the run via a dice roll to keep the maximum score consistent. 

. When the robot detects a victim and flashes the correct color LED during the detection performance, it can receive points for identification, and the points for identification are canceled if it flashes the wrong color LED on the same victim.

* Red victim: The robot must stop on the Red victim and blink with the Red LED (see <<construction>>) that is clearly visible to the referee for the full 5 seconds while stationary. The blink interval (ON: 500ms, OFF: 500ms) must be followed to successfully detect a victim.
* Green victim: The robot must stop on the Green victim and blink with the Green LED (see <<construction>>) that is clearly visible to the referee for the full 5 seconds while stationary. The blink interval (ON: 500ms, OFF: 500ms) must be followed to successfully detect a victim.

. The Reliability Bonus is a non-negative number and calculated from the number of successful victim identifications (SVI) and the total number of Lack of Progresses (LoP) as such:
 ⋆　(RELIABILITY BONUS) = (SVI) × 10 - (LoP) × 10

. Successful navigate a Speed Bump, The robot visits each tile with speed bumps, then visits  another tile, the robot is awarded 5 points. 

. Successful Checkpoint Navigation. A robot is awarded 10 points for each visited checkpoint. Refer to Section 5.4, “Scoring Run” for definition of visited tile. 

. Successful Exit Bonus. A robot is awarded 10 points for each victim successfully identified. The 'exit bonus' condition is satisfied when the robot returns to the starting tile and performs the following: On the starting tile, the robot has to stop and blink (ON: 1s, OFF: 1s) with the green and red LEDs used to identify victims (see Section 4.3, "Build") alternately (on for 1 second, off for 1 second) for at least 10 seconds. If the robot performs an "Exit Performance" on any tile, it must exit the game.

. No duplicate rewards. For example, suppose a robot successfully crosses a tile with speed bumps multiple times. In that case, only one successful speed bump crossing will be rewarded per tile. The same result applies to all other scoring rules. 

. Misidentification. If the robot performs the detection function outside the victim, 5 points will be deducted. The total score cannot be less than 0 points. 


=== End of Game
. A team may elect to stop the game early at any time. In this case, the team captain must indicate the team's desire to terminate the game to the referee. The team will be awarded all points earned up to the call for the end of the game. The referee will stop the time at the end of the game, which will be recorded as the game time.

. The game ends when: 
.. The 6 minutes of allowed game time expires  
.. The team captain calls the end of the game.
.. The robot performs the exit performance anywhere on the field.
