== RoboCupJunior International 2026 General Rules

These rules apply to the international RoboCupJunior competition.
However, regional, SuperRegional, and local tournaments may have
variations or adaptations to these rules to suit their specific
competition needs. It is important to check with the organizers of the
tournaments you are participating in to confirm which exact rules will
be in use.

If teams are unsure about any aspects of the General Rules or specific
League Rules, they are encouraged to inquire via the official
RoboCupJunior Forum for clarification: https://junior.forum.robocup.org/

For questions regarding any of the rules or RoboCupJunior in general, teams
can also reach out to the RoboCupJunior community through the https://robocup-junior.github.io/soccer-rules/discord/[official Discord Server].

=== Team Requirements

==== Team Size
*Minimum Team Size*: Teams must consist of at least 2 members.

*Maximum Team Size*:

* Soccer and Rescue Leagues: 4 members.

* OnStage League: 5 members.

Regional and SuperRegional competitions may define their own team sizes depending on their venue capacity and regional variations. Teams attending the International competition will only be able to have the maximum number of registered participants in the qualifying team.

*Shared Members and Robots*: No team member(s) or robot(s) may be
shared between teams.

==== Team Supervision
*Junior Mentor Requirement*: Each Junior team must have at least 
one Junior Mentor registered and attending with the team.

Mentors and Parent/Chaperones are responsible for supervising their teams
and maintain a duty of care/well being for their team members, as appropriate for their home region's regulations.
Any concerns regarding team member welfare should be brought to the attention of the event organizers immediately.

The Junior Mentor is expected to be present during all official competition events with their team.
They must not interact in an imposing manner with teams, robots, judges, or the judging process. Any incident considered inappropriate will be handled by the event organizers and may lead to disciplinary actions.

==== Age Requirements

*Junior Student Members:* Must be between 14 and 19 years old as of July 1st of the competition year.

*Junior Mentors and Parent/Chaperones:* Must be 19 years or older as of July 1st of the competition year.

==== Team Members

*Entry Leagues*: RoboCupJunior Entry leagues and other "Primary"
divisions (where minimum age may vary) are not run at the international
competition but feature in many regions and SuperRegional tournaments.

*Technical Roles*: Every team member must have a defined technical
role (mechanical/design, electrical/sensing, software etc.) and should
be able to explain their role during technical judging.

=== International Team Qualification Process
* To qualify for the International competition, each region’s Regional Representative will complete the Slot Allocation Process at the start of the Competition year. Regional Representatives can be found at the https://junior.robocup.org/gettingstarted/[Official Website].
* After the region’s local qualifying tournament, the Regional Representative 
will assign slots. Once confirmed by the RoboCupJunior organizers, the qualified teams will be invited to register through the official RoboCup Federation registration system.
* The qualification process differs depending on the size of each region, 
but slot allocation must strongly reflect results from regional competitions.
* If a region does not use or releases its allocated slots, Regional Representatives 
may request additional slots during a later stage of the allocation process.

=== Robot Requirements

==== Robot Communication

*Permitted Communication*: Communication between robots during
gameplay is allowed as long as it uses the 2.4GHz spectrum and its power
output does not exceed 100 mW EIRP (Effective Isotropic Radiated Power) under any circumstances.

*Responsibility*: Teams are responsible for managing their robot
communication. Spectrum availability is not guaranteed.

*Component Communication*: Communication between components of the
same robot is permitted.

*League Adaptability*: Each league may modify the robot communication
rules to ensure they meet their specific requirements.

==== Safety and Power Requirements

*Electrical Power*:

* Robots must not use mains electricity.

* Maximum allowed voltage: 48V DC or 25V AC RMS (Root Mean Square).

* Voltage must be easily measured during inspections, and measuring
points must be covered for safety or designed with safety considerations
in place.


*Battery Safety*:

* Lithium batteries must be stored in safety bags, and charging must be
supervised by team members in competition areas.

* Teams must follow safety protocols, including battery fire handling
and evacuation procedures.

*Robot Safety Design*:

* *Power Management*: Secure batteries, safe wiring, and emergency stop
functionality.

* *Mechanical Safety*: No sharp edges, pinch points, or other hazards.
Actuators must be appropriate for the robot’s size and function.

* *Hazardous Behavior*: Teams must report potentially dangerous robot
behaviors at least two weeks before a RoboCupJunior event.

=== Documentation and Sharing Requirements

==== RoboCupJunior Team Posters

*Purpose*: Posters are a tool for sharing robot designs and insights
with judges, teams, and the public. Posters will be hung in public
competition areas in the venue and digital copies or photographs will be
shared by RoboCupJunior after the competition.

*Size*: Posters must be no larger than A1 size (60 x 84 cm).

*Content*: Posters should summarize design documents and present the
robot’s capabilities in an engaging format.

==== Technical Description Video (See League Documentation)

*Content*:

* *Robotic Demonstration*: Show fully functional robot systems to
highlight technical aspects.

* *Design Process*: Explain design choices and team problem-solving
approaches.

* *Presentation*: Clear and high-quality, explaining innovative or
unusual techniques.

* *Innovation & Sustainability*: Highlight new technologies and
sustainable practices.

*Submission*: Guidelines will specify video length and deadlines per
league.

==== Sharing Team Resources

*Sharing*: Materials submitted by teams as part of the documentation
submission will be shared on GitHub repositories for the leagues:
https://github.com/robocup-junior

*Credit*: Teams must credit creators of external work and adhere to
licensing rules. The focus should remain on personal growth and
learning.

==== Plagiarism Guidelines

*External Code Use*: Teams are allowed to use external code but must
credit the original creators.

*Learning Priority*: Teams should prioritize learning and not use
complete solutions from others. Always pay attention to licensing rules.

==== Bill of Materials (BOM)

*Submission*: Teams must submit a BOM (Bill of Materials) listing major components and
materials used. 

*Details*: The BOM must include:

* Component name/description (e.g., part number).

* Supplier/source of the component (including PCBs/machined
components).

* Status (new/reused).

* Kit or custom-built.

* Price.

*Template*: A standardized BOM template will be provided with the
league documentation submissions for the international competition.

=== Spirit and Behavior

==== Behavior

All participants are expected to behave themselves and be considerate and polite
especially but not only towards other participants, volunteers, referees and
organizers of all Junior and Major Leagues as well as the host venue.

==== Code of Conduct
All organisers, volunteers, team members, mentors, supporters and visitors must abide by the RoboCup Federation Code of Conduct. Any instances where, a situation occurs that does not meet the code of conduct must be reported to a RoboCup Federation organisation member and will be investigated.

==== Mentoring and Onsite Assistance
Support from other teams, mentors, teachers, parents, sponsors, internet
communities etc. is a core part of how teams learn and grow.

To ensure fair competition and maximize learning it is required that none of the support they
receive does the work of competing for the team. A good indication is the team's
ability to explain not only what their robots' components do but also how they
do it.

==== Teams Onsite
* During the competition, only the official team members (maximum 4/5 depending on league) 
can represent the team at registration, setup-day, and have access to the competition areas for rounds and interviews. 
* There must be at least 2 team members on-site, unless a team can present evidence of extenuating circumstances, including proof of travel for other team members. Teams where only one participant presents at the venue will be able to compete, but will not be eligible for finals or awards. 
* It is the teams' responsibility to ensure that team member are present at the correct time and location for all scheduled activities.
* Teams are not allowed to communicate with or receive help virtually from external parties with the intention of impacting the team's performance during the competition areas. Virtually communicating includes but is not limited to extended phone calls, video calls, remote desktop control etc.
* Any team found to be in breach of these rules may be subject to disciplinary action.
* Teams are recommended  to seek help from other teams, or organizers if they are struggling with any issues onsite.

==== Violations

Teams, Team Mentors/Supporters or Team Members that repeatedly conduct themselves in an unacceptable way or in violation to the General or League Rules may be
disqualified from the tournament and asked to leave the venue.
